# Generated by Django 5.1.5 on 2025-02-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ascension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(related_name='users', through='ascension.UserInterest', to='ascension.interestcategory'),
        ),
    ]
